## Scrapping Denis

In [1]:
import Fonctions as Fct 
import Listes
import Generation_df as Gdf
import Nettoyage as Net

Donnees = Gdf.pd.DataFrame({"Date": [], "Chaine": [], "Part_de_marche": []})

Dates = Listes.date(31,12,6)
Chemins = Listes.chemin(Dates)

for i in range(len(Chemins)):
    arbre = Fct.arbre(Chemins[i])
    test = arbre.find("h1")
    test = str(test)
    if test != "<h1>Audiences TV du 10 décembre 2019 avec Tele 7</h1>" :
        V1 = Fct.Jour(arbre)
        V2 = Fct.Logo(arbre)
        V3 = Fct.Pdm(arbre)
        if len(V1) == 19 & len(V2) == 19 & len(V3) == 19:
            Donnees = Gdf.Donnee(V1,V2,V3,Donnees)
            
Donnees["Chaine"] = Net.recodage(Donnees["Chaine"], {'35_192"':"TF1",
                                                 '35_80" ':"France 3",
                                                '35_118"':"M6",
                                                 '35_4" h':"France 2",
                                                 '35_195"':"TMC",
                                                '35_47" ':"France 5",
                                                 '35_445"':"C8",
                                                '35_119"':"W9",
                                                 '35_446"':"TFX",
                                                '35_111"':"Arte",
                                                 '35_78" ':"France 4",
                                                '35_444"':"NRJ 12",
                                                 '35_458"':"C Star",
                                                '35_160"':"France O",
                                                 '35_482"':"Gulli",
                                                '35_1402':"RMC Story",
                                                '35_1404':"TF1 Series",
                                                 '35_1400':"RMC Decouverte",
                                                '35_1403':"6ter",
                                                '35_1399':"Cherie 25",
                                                 '35_1400':"RMC Decouverte",
                                                '35_1403':"6ter",
                                                '35_34" ': "Canal +",
                                                '35_234"': "LCP Public Senat",
                                                '35_1401': "L Equipe",
                                                '35_481"': "BFM TV"})

In [2]:
Donnees.to_csv('Part_marche.csv')

In [3]:
Donnees

                    Date          Chaine Part_de_marche
0      02 septembre 2014             TF1           31.7
1      02 septembre 2014        France 3           13.7
2      02 septembre 2014              M6           12.4
3      02 septembre 2014        France 2           11.6
4      02 septembre 2014             TMC            4.9
...                  ...             ...            ...
32143   08 décembre 2019  RMC Decouverte            1.2
32144   08 décembre 2019              C8            1.2
32145   08 décembre 2019           Gulli            0.9
32146   08 décembre 2019       RMC Story            0.5
32147   08 décembre 2019        France 4

[32148 rows x 3 columns]

## Scrapping Evelore

In [4]:
import Fonctions_prgm_TV as fct 
import generation_data as gen
import url

Data = gen.pd.DataFrame({"Date": [],"Jour": [], "Chaine": [], "Heure_prgm1": [], "Titre_prgm1": [], "Type_prgm1": [],
                        "Duree_prgm1": [], "Nbre_episodes_prgm1": [], "Age_conseille_prgm1": [],"Heure_prgm2": [],
                        "Titre_prgm2": [], "Type_prgm2": [], "Duree_prgm2": [], "Nbre_episodes_prgm2": [],
                         "Age_conseille_prgm2": []})

Dates = url.dates(2019)
Chemins = url.chemin(Dates)

for i in range(len(Chemins)):
    arbre = fct.tree(Chemins[i])
    V1 = fct.date(arbre)
    V2 = fct.jour(arbre)
    V3 = fct.chaines(arbre)
    V4 = fct.heures1(arbre)
    V5 = fct.titres1(arbre)
    V6 = fct.type_prgm1(arbre)
    V7 = fct.temps_prgm1(arbre)
    V8 = fct.nbre_ep1(arbre)
    V9 = fct.ages1(arbre)
    V10 = fct.heures2(arbre)
    V11 = fct.titres2(arbre)
    V12 = fct.type_prgm2(arbre)
    V13 = fct.temps_prgm2(arbre)
    V14 = fct.nbre_ep2(arbre)
    V15 = fct.ages2(arbre)
    Data = gen.Donnee(V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,Data)

Types = {
    "['" : "NA",
    "[' cat-selection-obs" : "NA",
    "['ballet" : "Ballet",
    "['ceremonie" : "Ceremonie",
    "['clips" : "Clips",
    "['concert" : "Concert",
    "['court-metrage" : "Court-metrage",
    "['danse" : "Danse",
    "['debat" : "Debat",
    "['dessin-anime" : "Dessin-anime",
    "['divertissement" : "Divertissement",
    "['divertissement cat-selection-obs" : "Divertissement",
    "['divertissement cat-selection-o" : "Divertissement",
    "['divertissement cat-selection-o']" : "Divertissement",
    "['documentaire" : "Documentaire",
    "['documentaire cat-selection-obs" : "Documentaire",
    "['documentaire cat-selection-obs']" : "Documentaire",
    "['emission-religieuse" : "Emission religieuse",
    "['film" : "Film",
    "['film cat-selection-obs" : "Film",
    "['fin-des-emissions" : "Fin des emissions",
    "['gala" : "Gala",
    "['information" : "Information",
    "['jeu" : "Jeu",
    "['jeu cat-selection-obs" : "Jeu",
    "['journal" : "Journal",
    "['magazine" : "Magazine",
    "['magazine cat-selection-obs" : "Magazine",
    "['making-of" : "Making-of",
    "['musique" : "Musique",
    "['opera" : "Opera",
    "['opera cat-selection-obs" : "Opera",
    "['prog-court" : "Programme Court",
    "['reportage" : "Reportage",
    "['serie-tv cat-selection-obs" : "Serie TV",
    "['serie-tv" : "Serie TV",
    "['spectacle" : "Spectacle",
    "['spectacle cat-selection-obs" : "Spectacle",
    "['sport" : "Sport",
    "['sport cat-selection-obs" : "Sport",
    "['talk-show" : "Talk-Show",
    "['telefilm" : "Telefilm",
    "['telefilm cat-selection-obs" : "Telefilm",
    "['telerealite" : "Telerealitee",
    "['telerealite cat-selection-obs" : "Telerealitee", 
    "['theatre" : "Theatre"
    }

Chaines = {
    " tf1" : "TF1",
    " france 2" : "France 2",
    " france 3" : "France 3",
    " canal +" : "Canal +",
    " france 5" : "France 5",
    " m6" : "M6",
    " arte" : "Arte",
    " c8" : "C8",
    " w9" : "W9",
    " tmc" : "TMC",
    " tfx" : "TFX",
    " nrj 12" : "NRJ 12",
    " public senat - lcp an" : "LCP Public Senat",
    " france 4" : "France 4",
    " bfm tv" : "BFM TV",
    " cnews" : "C News",
    " cstar" : "C Star",
    " gulli" : "Gulli",
    " france ô" : "France O",
    " france Ô" : "France O",
    " tf1 séries films" : "TF1 Series",
    " 6ter" : "6ter",
    " l'equipe" : "L Equipe",
    " rmc story" : "RMC Story",
    " rmc decouverte" : "RMC Decouverte",
    " cherie 25" : "Cherie 25",
    " rtl 9" : "RTL 9"
    }

Data["Type_prgm1"] = Data["Type_prgm1"].map(Types)
Data["Type_prgm2"] = Data["Type_prgm2"].map(Types)
Data["Chaine"] = Data["Chaine"].map(Chaines)
    
for i, row in Data.iterrows():
    if row['Titre_prgm1']==row['Titre_prgm2']:
        row['Type_prgm2']=row['Type_prgm1']

In [5]:
Data

,Date,Jour,Chaine,Heure_prgm1,Titre_prgm1,Type_prgm1,Duree_prgm1,Nbre_episodes_prgm1,Age_conseille_prgm1,Heure_prgm2,Titre_prgm2,Type_prgm2,Duree_prgm2,Nbre_episodes_prgm2,Age_conseille_prgm2
0,08 octobre 2014,mercredi,TF1,20.55,Blacklist,Serie TV,110,2,-10 ans,22.40,Arrow,Serie TV,100,3,-10 ans
1,08 octobre 2014,mercredi,France 2,20.50,Les hommes de l'ombre,Serie TV,120,2,Tout public,22.40,Un soir à la tour Eiffel,Magazine,100,0,Tout public
2,08 octobre 2014,mercredi,France 3,20.45,Des racines et des ailes,Magazine,115,0,Tout public,23.36,Le comte Ory,Opera,144,0,Tout public
3,08 octobre 2014,mercredi,Canal +,20.55,Diana,Film,110,0,Tout public,22.45,9 mois ferme,Film,80,0,Tout public
4,08 octobre 2014,mercredi,France 5,20.40,La maison France 5,Magazine,60,0,Tout public,21.40,"Silence, ça pousse !",Magazine,49,0,Tout public
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47245,10 décembre 2019,mardi,TF1 Series,21.00,Le Bazar de la Charité,Serie TV,130,2,-10 ans,22.55,La tragique histoire de l'incendie du Bazar de...,Documentaire,75,0,Tout public
47246,10 décembre 2019,mardi,L Equipe,21.00,La grande soirée,Magazine,110,0,Tout public,22.50,L'Équipe du soir,Magazine,70,0,Tout public
47247,10 décembre 2019,mardi,RMC Story,20.55,The Glades,Serie TV,110,2,-10 ans,22.45,Indices,Magazine,140,2,-10 ans
47248,10 décembre 2019,mardi,RMC Decouverte,20.55,Bâtisseurs de l'ancien monde,Documentaire,195,0,Tout public,00.10,La révélation des pyramides,Documentaire,120,2,Tout public
47249,10 décembre 2019,mardi,Cherie 25,21.05,Snapped : vacances mortelles,Magazine,120,6,-10 ans,NA,Snapped : vacances mortelles,Magazine,NA,6,Tout public

In [6]:
Data.to_csv('Prgm_TV.csv')

## Fusion

In [7]:
import pandas as pd
fusion = pd.merge(Data,Donnees,on=["Date","Chaine"], how="outer")

In [8]:
fusion

,Date,Jour,Chaine,Heure_prgm1,Titre_prgm1,Type_prgm1,Duree_prgm1,Nbre_episodes_prgm1,Age_conseille_prgm1,Heure_prgm2,Titre_prgm2,Type_prgm2,Duree_prgm2,Nbre_episodes_prgm2,Age_conseille_prgm2,Part_de_marche
0,08 octobre 2014,mercredi,TF1,20.55,Blacklist,Serie TV,110,2,-10 ans,22.40,Arrow,Serie TV,100,3,-10 ans,24.4
1,08 octobre 2014,mercredi,France 2,20.50,Les hommes de l'ombre,Serie TV,120,2,Tout public,22.40,Un soir à la tour Eiffel,Magazine,100,0,Tout public,13.1
2,08 octobre 2014,mercredi,France 3,20.45,Des racines et des ailes,Magazine,115,0,Tout public,23.36,Le comte Ory,Opera,144,0,Tout public,12
3,08 octobre 2014,mercredi,Canal +,20.55,Diana,Film,110,0,Tout public,22.45,9 mois ferme,Film,80,0,Tout public,NaN
4,08 octobre 2014,mercredi,France 5,20.40,La maison France 5,Magazine,60,0,Tout public,21.40,"Silence, ça pousse !",Magazine,49,0,Tout public,2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48547,17 juin 2019,NaN,"35_"" hr",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
48548,18 juin 2019,NaN,"35_"" hr",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
48549,30 juin 2019,NaN,"35_"" hr",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
48550,28 juillet 2019,NaN,Gulli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5
48551,13 septembre 2019,NaN,"35_"" hr",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [9]:
fusion.to_csv('Base_donnees.csv')

# Transformation des données

In [50]:
import pandas as pd

In [56]:
resultat = pd.read_csv("Base_donnees.csv")

In [52]:
resultat.Chaine.unique()

array(['TF1', 'France 2', 'France 3', 'Canal +', 'France 5', 'M6', 'Arte',
       'C8', 'W9', 'TMC', 'TFX', 'NRJ 12', 'LCP Public Senat', 'France 4',
       'BFM TV', 'C News', 'C Star', 'Gulli', 'France O', '6ter',
       'TF1 Series', 'L Equipe', 'RMC Story', 'RMC Decouverte',
       'Cherie 25', 'RTL 9', nan, '35_" hr'], dtype=object)

In [53]:
#Data frame par chaîne
D01 = resultat.loc[resultat['Chaine']=="TF1",:]
D02 = resultat.loc[resultat['Chaine']=="France 2",:]
D03 = resultat.loc[resultat['Chaine']=="France 3",:]
D04 = resultat.loc[resultat['Chaine']=="Canal +",:]
D05 = resultat.loc[resultat['Chaine']=="France 5",:]
D06 = resultat.loc[resultat['Chaine']=="M6",:]
D07 = resultat.loc[resultat['Chaine']=="Arte",:]
D08 = resultat.loc[resultat['Chaine']=="C8",:]
D09 = resultat.loc[resultat['Chaine']=="W9",:]
D10 = resultat.loc[resultat['Chaine']=="TMC",:]
D11 = resultat.loc[resultat['Chaine']=="TFX",:]
D12 = resultat.loc[resultat['Chaine']=="NRJ 12",:]
D13 = resultat.loc[resultat['Chaine']=="LCP Public Senat",:]
D14 = resultat.loc[resultat['Chaine']=="France 4",:]
D15 = resultat.loc[resultat['Chaine']=="BFM TV",:]
D16 = resultat.loc[resultat['Chaine']=="C News",:]
D17 = resultat.loc[resultat['Chaine']=="C Star",:]
D18 = resultat.loc[resultat['Chaine']=="Gulli",:]
D19 = resultat.loc[resultat['Chaine']=="France O",:]
D20 = resultat.loc[resultat['Chaine']=="TF1 Series",:]
D21 = resultat.loc[resultat['Chaine']=="L Equipe",:]
D22 = resultat.loc[resultat['Chaine']=="6ter",:]
D23 = resultat.loc[resultat['Chaine']=="RMC Story",:]
D24 = resultat.loc[resultat['Chaine']=="RMC Decouverte",:]
D25 = resultat.loc[resultat['Chaine']=="Cherie 25",:]

In [54]:
D25

,Unnamed: 0,Date,Jour,Chaine,Heure_prgm1,Titre_prgm1,Type_prgm1,Duree_prgm1,Nbre_episodes_prgm1,Age_conseille_prgm1,Heure_prgm2,Titre_prgm2,Type_prgm2,Duree_prgm2,Nbre_episodes_prgm2,Age_conseille_prgm2,Part_de_marche
24,24,08 octobre 2014,mercredi,Cherie 25,20.45,Les boeuf-carottes,Serie TV,200,3.0,NaN,NaN,Les boeuf-carottes,Serie TV,NaN,3.0,NaN,NaN
49,49,09 octobre 2014,jeudi,Cherie 25,20.45,Les Tudors,Serie TV,100,6.0,-10 ans,NaN,Les Tudors,Serie TV,NaN,6.0,NaN,NaN
74,74,10 octobre 2014,vendredi,Cherie 25,20.45,Sans tabou,Magazine,170,3.0,NaN,NaN,Sans tabou,Magazine,NaN,3.0,NaN,NaN
99,99,11 octobre 2014,samedi,Cherie 25,20.45,Stars et vérités,Magazine,180,3.0,NaN,NaN,Stars et vérités,Magazine,NaN,3.0,NaN,NaN
124,124,12 octobre 2014,dimanche,Cherie 25,20.45,Une famille au top,Telerealitee,105,0.0,NaN,22.3,Ma nouvelle famille,Telerealitee,100,4.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48176,48176,29 novembre 2019,NaN,Cherie 25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5
48197,48197,30 novembre 2019,NaN,Cherie 25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.2
48226,48226,01 décembre 2019,NaN,Cherie 25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
48227,48227,01 décembre 2019,NaN,Cherie 25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
48255,48255,02 décembre 2019,NaN,Cherie 25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.2

In [57]:
fusion = pd.merge(D01,D02, on="Date")
fusion = pd.merge(fusion,D03, on="Date")
fusion = pd.merge(fusion,D04, on="Date")
fusion = pd.merge(fusion,D05, on="Date")
fusion = pd.merge(fusion,D06, on="Date")
fusion = pd.merge(fusion,D07, on="Date")
fusion = pd.merge(fusion,D08, on="Date")
fusion = pd.merge(fusion,D09, on="Date")
fusion = pd.merge(fusion,D10, on="Date")
fusion = pd.merge(fusion,D11, on="Date")
fusion = pd.merge(fusion,D12, on="Date")
fusion = pd.merge(fusion,D13, on="Date")
fusion = pd.merge(fusion,D14, on="Date")
fusion = pd.merge(fusion,D15, on="Date")
fusion = pd.merge(fusion,D16, on="Date")
fusion = pd.merge(fusion,D17, on="Date")
fusion = pd.merge(fusion,D18, on="Date")
fusion = pd.merge(fusion,D19, on="Date")
fusion = pd.merge(fusion,D20, on="Date")
fusion = pd.merge(fusion,D21, on="Date")
fusion = pd.merge(fusion,D22, on="Date")
fusion = pd.merge(fusion,D23, on="Date")
fusion = pd.merge(fusion,D24, on="Date")
fusion = pd.merge(fusion,D25, on="Date")

MemoryError: Unable to allocate array with shape (221, 1246929) and data type object

In [ ]:
fusion

In [32]:
fusion = pd.merge(D01,D02, on="Date")
fusion = pd.merge(fusion,D03, on="Date")
fusion = pd.merge(fusion,D04, on="Date")

In [34]:
fusion.shape

(4, 65)

In [36]:
fusion

,Unnamed: 0_x,Date,Jour_x,Chaine_x,Heure_prgm1_x,Titre_prgm1_x,Type_prgm1_x,Duree_prgm1_x,Nbre_episodes_prgm1_x,Age_conseille_prgm1_x,...,Duree_prgm1_y,Nbre_episodes_prgm1_y,Age_conseille_prgm1_y,Heure_prgm2_y,Titre_prgm2_y,Type_prgm2_y,Duree_prgm2_y,Nbre_episodes_prgm2_y,Age_conseille_prgm2_y,Part_de_marche_y
0,9264,26 février 2016,vendredi,TF1,20.55,Koh-Lanta,Jeu,140 mn,NaN,NaN,...,185 mn,NaN,NaN,0.0,Après les César,Magazine,40 mn,NaN,NaN,11.9
1,9891,28 mars 2016,lundi,TF1,20.55,Clem,Serie TV,115 mn,NaN,NaN,...,100 mn,2.0,-10 ans,22.4,Frontières : la grande illusion ?,Magazine,55 mn,NaN,NaN,4
2,16275,24 février 2017,vendredi,TF1,20.55,Stars sous hypnose,Divertissement,300 mn,2.0,NaN,...,180 mn,NaN,NaN,0.0,Médecin de campagne,Film,100 mn,NaN,NaN,10.5
3,25960,22 février 2019,vendredi,TF1,21.00,L'aventure Robinson,Telerealitee,155 mn,NaN,NaN,...,180 mn,NaN,NaN,0.0,Les Tuche 3,Film,90 mn,NaN,NaN,9.6

In [35]:
fusion.to_csv('essai.csv')

In [37]:
fusion = pd.merge(D01,D02, on="Date",how="outer")
fusion = pd.merge(fusion,D03, on="Date",how="outer")
fusion = pd.merge(fusion,D04, on="Date",how="outer")
fusion = pd.merge(fusion,D05, on="Date",how="outer")
fusion = pd.merge(fusion,D06, on="Date",how="outer")
fusion = pd.merge(fusion,D07, on="Date",how="outer")
fusion = pd.merge(fusion,D08, on="Date",how="outer")
fusion = pd.merge(fusion,D09, on="Date",how="outer")
fusion = pd.merge(fusion,D10, on="Date",how="outer")
fusion = pd.merge(fusion,D11, on="Date",how="outer")
fusion = pd.merge(fusion,D12, on="Date",how="outer")

In [38]:
fusion

,Unnamed: 0_x,Date,Jour_x,Chaine_x,Heure_prgm1_x,Titre_prgm1_x,Type_prgm1_x,Duree_prgm1_x,Nbre_episodes_prgm1_x,Age_conseille_prgm1_x,...,Duree_prgm1_y,Nbre_episodes_prgm1_y,Age_conseille_prgm1_y,Heure_prgm2_y,Titre_prgm2_y,Type_prgm2_y,Duree_prgm2_y,Nbre_episodes_prgm2_y,Age_conseille_prgm2_y,Part_de_marche_y
0,0,08 octobre 2014,mercredi,TF1,20.55,Blacklist,Serie TV,110 mn,2.0,-10 ans,...,100 mn,NaN,-12 ans,22.30,"Le projet Philadelphia, l'expérience interdite",Telefilm,100 mn,NaN,-10 ans,2
1,19,09 octobre 2014,jeudi,TF1,20.55,Crossing Lines,Serie TV,120 mn,4.0,-10 ans,...,210 mn,3.0,NaN,NaN,Tellement vrai,Magazine,NaN,3.0,NaN,1.8
2,38,10 octobre 2014,vendredi,TF1,20.55,Danse avec les stars,Divertissement,140 mn,NaN,NaN,...,220 mn,3.0,NaN,NaN,Sauveur Giordano,Serie TV,NaN,3.0,NaN,2.6
3,57,11 octobre 2014,samedi,TF1,20.35,Match amical,Sport,130 mn,NaN,NaN,...,120 mn,NaN,NaN,22.50,Le super bêtisier de l'année,Divertissement,210 mn,2.0,NaN,1.3
4,76,12 octobre 2014,dimanche,TF1,20.55,"The Dark Knight, le chevalier noir",Film,170 mn,NaN,-10 ans,...,115 mn,NaN,-10 ans,22.45,Total Recall,Film,110 mn,NaN,-12 ans,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71229,31099,16 novembre 2019,samedi,TF1,21.05,Danse avec les stars,Divertissement,115 mn,NaN,NaN,...,50 mn,1.0,NaN,NaN,Superstore,Serie TV,NaN,1.0,NaN,0.4
71230,31118,17 novembre 2019,dimanche,TF1,20.35,Éliminatoires de l'Euro 2020,Sport,125 mn,NaN,NaN,...,135 mn,NaN,NaN,23.20,Quatre mariages et un enterrement,Film,135 mn,NaN,NaN,1.7
71231,31137,18 novembre 2019,lundi,TF1,21.05,Le Bazar de la charité,Serie TV,150 mn,2.0,-10 ans,...,110 mn,NaN,-10 ans,22.55,"Crimes & faits divers, le prime",Magazine,125 mn,NaN,-10 ans,2.3
71232,31156,19 novembre 2019,mardi,TF1,21.05,S.W.A.T,Serie TV,90 mn,4.0,-10 ans,...,125 mn,NaN,-10 ans,23.10,21 Jump Street,Film,125 mn,NaN,-10 ans,1.7
71233,31175,20 novembre 2019,mercredi,TF1,21.05,Good Doctor,Serie TV,110 mn,2.0,NaN,...,110 mn,NaN,-12 ans,22.55,XIII,Serie TV,220 mn,2.0,-10 ans,1.8

In [39]:
fusion.shape

(71234, 193)

In [40]:
fusion.to_csv('essai.csv')